services:
  backend:
    build: .
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    volumes:
      - .:/code

  frontend:
    image: ghcr.io/in2siders/frontend-web:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://backend:5000

networks:
  app-network:
    driver: bridge
